//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCode is unique in database..
        /// </summary>
        public static string ErrorService_DuplicateCustomerCode_dev {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateCustomerCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép trùng..
        /// </summary>
        public static string ErrorService_DuplicateCustomerCode_user {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateCustomerCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is unique in database..
        /// </summary>
        public static string ErrorService_DuplicateEmail_dev {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmail_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép trùng.
        /// </summary>
        public static string ErrorService_DuplicateEmail_user {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmail_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is unique in database..
        /// </summary>
        public static string ErrorService_DuplicateEmployeeCode_dev {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmployeeCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép trùng..
        /// </summary>
        public static string ErrorService_DuplicateEmployeeCode_user {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmployeeCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDentifyNumber is unique in database..
        /// </summary>
        public static string ErrorService_DuplicateIdNumber_dev {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateIdNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/ Căn cước không được phép trùng..
        /// </summary>
        public static string ErrorService_DuplicateIdNumber_user {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateIdNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is unique in database..
        /// </summary>
        public static string ErrorService_DuplicatePhoneNumber_dev {
            get {
                return ResourceManager.GetString("ErrorService_DuplicatePhoneNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép trùng..
        /// </summary>
        public static string ErrorService_DuplicatePhoneNumber_user {
            get {
                return ResourceManager.GetString("ErrorService_DuplicatePhoneNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCode is not null in database..
        /// </summary>
        public static string ErrorService_NullCustomerCode_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullCustomerCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống..
        /// </summary>
        public static string ErrorService_NullCustomerCode_user {
            get {
                return ResourceManager.GetString("ErrorService_NullCustomerCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not null in database..
        /// </summary>
        public static string ErrorService_NullEmail_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullEmail_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép để trống..
        /// </summary>
        public static string ErrorService_NullEmail_user {
            get {
                return ResourceManager.GetString("ErrorService_NullEmail_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is not null in database..
        /// </summary>
        public static string ErrorService_NullEmployeeCode_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullEmployeeCode_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string ErrorService_NullEmployeeCode_user {
            get {
                return ResourceManager.GetString("ErrorService_NullEmployeeCode_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is not null in database..
        /// </summary>
        public static string ErrorService_NullFullName_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullFullName_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống..
        /// </summary>
        public static string ErrorService_NullFullName_user {
            get {
                return ResourceManager.GetString("ErrorService_NullFullName_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDentifyNumber is not null in database..
        /// </summary>
        public static string ErrorService_NullIdNumber_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullIdNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND/ Căn cước không được phép để trống..
        /// </summary>
        public static string ErrorService_NullIdNumber_user {
            get {
                return ResourceManager.GetString("ErrorService_NullIdNumber_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is not null in database..
        /// </summary>
        public static string ErrorService_NullPhoneNumber_dev {
            get {
                return ResourceManager.GetString("ErrorService_NullPhoneNumber_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép để trống..
        /// </summary>
        public static string ErrorService_NullPhoneNumber_user {
            get {
                return ResourceManager.GetString("ErrorService_NullPhoneNumber_user", resourceCulture);
            }
        }
    }
}
